version: '3.8'

services:
  # If you want to use a different database you can add your DB container here

  timeline-api:
    build:
      context: ./timeline_service/
    ports:
      - 8000:8000

  test-runner:
    build:
      context: ./tests/
    environment:
      - TIMELINE_API_BASE_URL=http://timeline-api:8000
